language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

before_script:
  - psql -c "CREATE DATABASE diesel_factories_test;" -U postgres
  - diesel migration run --database-url postgresql://localhost:5432/diesel_factories_test
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - cargo test --all
