language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

before_script:
  - psql -c "CREATE DATABASE diesel_factories_test;" -U postgres
  - rustup component add rustfmt-preview

script:
  - cargo fmt -- --check
  - cargo test --all
